fix error from npcCreate()
CFC-Servers/cfc_e2_lib pull request #64
Opened 2021-01-04 00:53 UTC by StrawWagen

added 2 lines, tested, and it works.

2021-01-07 19:20 UTC, brandonsturgeon requested changes
Just a quick fixup and it's good to go 👍

2021-01-07 19:20 UTC, brandonsturgeon commented on lua/entities/gmod_wire_expression2/core/custom/cfc_npc.lua
> +    position = Vector( positionIn[1], positionIn[2], positionIn[3] )
```suggestion
e2function entity npcCreate( string npcClass, vector position )
    if not hasAccess( self.player, 1 ) then return NULL end
    position = Vector( position[1], position[2], position[3] )

    local npc = ents.Create( npcClass )
    if not isValidNpc( npc ) then return NULL end
```

2021-01-07 19:20 UTC, brandonsturgeon commented on lua/entities/gmod_wire_expression2/core/custom/cfc_npc.lua
> +    position = Vector( positionIn[1], positionIn[2], positionIn[3] )
Same comment as the last one

2021-01-07 19:48 UTC, StrawWagen commented
latest version has been tested, works without errors

2021-01-07 19:53 UTC, brandonsturgeon commented
FYI you were previously defining `position` as a global variable, but the refactor solved that indirectly

2021-01-07 19:56 UTC, brandonsturgeon requested changes

2021-01-07 19:56 UTC, brandonsturgeon commented on lua/entities/gmod_wire_expression2/core/custom/cfc_npc.lua
> +    position = Vector( positionIn[1], positionIn[2], positionIn[3] )
If you really prefer `positionIn` over `position`, then this needs to be a local variable

```suggestion
    local position = Vector( positionIn[1], positionIn[2], positionIn[3] )
```

2021-01-07 19:56 UTC, brandonsturgeon commented on lua/entities/gmod_wire_expression2/core/custom/cfc_npc.lua
> +
```suggestion
```

2021-01-07 19:56 UTC, brandonsturgeon commented on lua/entities/gmod_wire_expression2/core/custom/cfc_npc.lua
> +    position = Vector( positionIn[1], positionIn[2], positionIn[3] )
```suggestion
    local position = Vector( positionIn[1], positionIn[2], positionIn[3] )
```

2021-01-08 18:57 UTC, brandonsturgeon approved these changes

2021-01-08 18:57 UTC, merged